CREATE TABLE `User` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Username` VARCHAR(255) NOT NULL UNIQUE,
	`Password` VARCHAR(255) NOT NULL,
	`Email` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `Oil` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NOT NULL UNIQUE,
	`ProductID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `Blend` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NOT NULL UNIQUE,
	`ProductID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `Blend_Has_Oil` (
	`CompositeID` VARCHAR(255) NOT NULL,
	`OilID` INT NOT NULL,
	`BlendID` INT NOT NULL,
	PRIMARY KEY (`CompositeID`)
);

CREATE TABLE `Order` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Price` INT NOT NULL AUTO_INCREMENT,
	`User` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `Product` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`IsBlend` BINARY NOT NULL,
	`Name` VARCHAR(255) NOT NULL,
	`Price` INT NOT NULL,
	`Purpose` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `Order_Has_Product` (
	`CompositeID` VARCHAR(255) NOT NULL,
	`OrderID` INT NOT NULL,
	`ProductID` INT NOT NULL,
	PRIMARY KEY (`CompositeID`)
);

ALTER TABLE `Oil` ADD CONSTRAINT `Oil_fk0` FOREIGN KEY (`ProductID`) REFERENCES `Product`(`ID`);

ALTER TABLE `Blend` ADD CONSTRAINT `Blend_fk0` FOREIGN KEY (`ProductID`) REFERENCES `Product`(`ID`);

ALTER TABLE `Blend_Has_Oil` ADD CONSTRAINT `Blend_Has_Oil_fk0` FOREIGN KEY (`OilID`) REFERENCES `Oil`(`ID`);

ALTER TABLE `Blend_Has_Oil` ADD CONSTRAINT `Blend_Has_Oil_fk1` FOREIGN KEY (`BlendID`) REFERENCES `Blend`(`ID`);

ALTER TABLE `Order` ADD CONSTRAINT `Order_fk0` FOREIGN KEY (`User`) REFERENCES `User`(`ID`);

ALTER TABLE `Order_Has_Product` ADD CONSTRAINT `Order_Has_Product_fk0` FOREIGN KEY (`OrderID`) REFERENCES `Order`(`ID`);

ALTER TABLE `Order_Has_Product` ADD CONSTRAINT `Order_Has_Product_fk1` FOREIGN KEY (`ProductID`) REFERENCES `Product`(`ID`);

