# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ailment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Ailment', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ailment Name', help_text='The name of the ailment', max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Order', primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=10.0, max_digits=19)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Product', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Oil Name', help_text='The name of the product', max_length=200, verbose_name='name')),
                ('description', models.CharField(blank=True, default='An oil that treats ailments', help_text='The description of the product', max_length=300, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=19)),
                ('isBlend', models.BooleanField(default=False)),
                ('ailments', models.ManyToManyField(help_text='Select the ailments this product treats', related_name='Ailments', to='catalog.Ailment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(help_text='Select the products in this order', related_name='Products', to='catalog.Product'),
        ),
    ]
