# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='An oil that treats ailments', help_text='The description of the product', max_length=1000, verbose_name='description'),
        ),
    ]
